# Installs

## Open notebook in:
| Colab                                 |  Gradient                                                                                                                                         |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/https://github.com/Nicolepcx/transformers-the-definitive-guide/blob/main/CH01/ch01_embeddings.ipynb)                                              | [![Gradient](https://assets.paperspace.io/img/gradient-badge.svg)](https://console.paperspace.com//github.com/Nicolepcx/transformers-the-definitive-guide/blob/main/CH01/ch01_embeddings.ipynb)|             

# About this notebook


In this notebook you can have a look at the embeddings in an LLM as introduced in the book.


# Imports

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

In [ ]:
# Load tokenizer and model from Hugging Face
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

# Our sentence
sentence = "The Transformer has revolutionized NLP."

# Tokenize the sentence
inputs = tokenizer(sentence, return_tensors='pt')


# Get the input IDs and pass them through the model to get the embeddings
input_ids = inputs['input_ids']

print(input_ids)
outputs = model(input_ids)

# The last hidden state is the embeddings of the tokens
embeddings = outputs.last_hidden_state
print(embeddings)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tensor([[[-0.5249, -0.2210,  0.2696,  ..., -0.4204,  0.2605,  0.6457],
         [-0.6665, -0.4994,  0.4651,  ..., -0.2517,  0.2334,  0.0176],
         [ 0.8416, -2.0561,  0.8323,  ..., -0.2709, -0.1999, -0.1918],
         ...,
         [-0.4018, -0.6402,  0.7791,  ..., -0.0290, -0.4070,  0.2974],
         [-0.3327, -0.8091, -0.0304,  ...,  0.4745,  0.3230, -0.5991],
         [ 0.4928, -0.0878, -0.0971,  ...,  0.1629, -0.7012, -0.3848]]],
       grad_fn=<NativeLayerNormBackward0>)


In [ ]:
input_ids.shape

torch.Size([1, 11])

In [ ]:
input_ids

tensor([[  101,  1996, 10938,  2121,  2038,  4329,  3550, 17953,  2361,  1012,
           102]])

In [ ]:
# Load tokenizer and model from Hugging Face
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

# Our sentence
sentence = "The Transformer has revolutionized NLP."

# Tokenize the sentence
inputs = tokenizer(sentence, return_tensors='pt')
input_ids = inputs['input_ids']

# Print out the tokens and their corresponding IDs
print('Token IDs:', input_ids)

# Get the embeddings for the input IDs
with torch.no_grad(): # We don't need gradients for this operation
    outputs = model(input_ids)
    embeddings = outputs.last_hidden_state

# Choose a token to display its embedding, for example, the first token
token_id = input_ids[0][1]  # Get the token ID for the second token (index 1)
token_embedding = embeddings[0][1]  # Get the embedding for the second token

print(f"Embedding for token ID {token_id}:", token_embedding)


Token IDs: tensor([[  101,  1996, 10938,  2121,  2038,  4329,  3550, 17953,  2361,  1012,
           102]])
Embedding for token ID 1996: tensor([-6.6654e-01, -4.9943e-01,  4.6507e-01, -2.4188e-02, -2.9564e-01,
        -2.3937e-01, -1.2124e-02,  5.2619e-01, -2.0337e-01, -3.1798e-01,
        -1.6313e-01,  4.7622e-01, -5.8335e-02,  1.0027e+00, -8.1636e-02,
         3.0922e-01, -3.6349e-02, -6.7692e-02,  1.6409e-01,  2.5328e-01,
        -6.5357e-01, -3.3515e-01,  8.9445e-02,  3.8793e-01,  1.8404e-02,
        -1.1392e-01, -9.6032e-02,  3.3755e-01, -5.6097e-02,  3.0721e-02,
        -1.2716e-01, -1.9835e-01, -3.1127e-01, -6.3842e-01,  3.5176e-01,
        -1.4550e-01, -4.6860e-01, -9.1851e-01, -4.8431e-01,  2.0002e-01,
        -2.3034e-01, -3.3772e-01,  3.3853e-01,  2.6485e-01, -2.4186e-01,
        -8.4571e-01, -2.7504e-01, -2.3496e-01, -1.3133e-01, -9.6998e-01,
        -7.0320e-01, -3.9584e-01,  2.0269e-01,  6.6703e-01, -4.8924e-01,
         5.2281e-01,  3.7298e-01, -3.7544e-01,  5.2407e-01, 

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Load tokenizer and model from Hugging Face
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

# Our sentence
sentence = "The Transformer has revolutionized NLP."

# Tokenize the sentence
inputs = tokenizer(sentence, return_tensors='pt')

# Get the input IDs and pass them through the model to get the embeddings
input_ids = inputs['input_ids']
outputs = model(input_ids)

# The last hidden state is the embedding of the tokens
embeddings = outputs.last_hidden_state
print(embeddings)

# Accessing the positional embeddings (indirectly)
# Note: This is more of an illustrative purpose. For specific models like BERT, positional embeddings are not directly exposed.
# However, you can access the model's embeddings layer and look at the weights for the positional embeddings.
positional_embeddings = model.embeddings.position_embeddings.weight
print(positional_embeddings)

# If you want to see the effect of positional embeddings on a specific token,
# you can compare the embeddings with and without positional information.
# Note: This is a conceptual demonstration and may not directly apply as is.
token_without_position = model.embeddings.word_embeddings(input_ids[0])
token_with_position = embeddings[0]

print("Token without positional information:", token_without_position)
print("Token with positional information:", token_with_position)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tensor([[[-0.5249, -0.2210,  0.2696,  ..., -0.4204,  0.2605,  0.6457],
         [-0.6665, -0.4994,  0.4651,  ..., -0.2517,  0.2334,  0.0176],
         [ 0.8416, -2.0561,  0.8323,  ..., -0.2709, -0.1999, -0.1918],
         ...,
         [-0.4018, -0.6402,  0.7791,  ..., -0.0290, -0.4070,  0.2974],
         [-0.3327, -0.8091, -0.0304,  ...,  0.4745,  0.3230, -0.5991],
         [ 0.4928, -0.0878, -0.0971,  ...,  0.1629, -0.7012, -0.3848]]],
       grad_fn=<NativeLayerNormBackward0>)
Parameter containing:
tensor([[ 1.7505e-02, -2.5631e-02, -3.6642e-02,  ...,  3.3437e-05,
          6.8312e-04,  1.5441e-02],
        [ 7.7580e-03,  2.2613e-03, -1.9444e-02,  ...,  2.8910e-02,
          2.9753e-02, -5.3247e-03],
        [-1.1287e-02, -1.9644e-03, -1.1573e-02,  ...,  1.4908e-02,
          1.8741e-02, -7.3140e-03],
        ...,
        [ 1.7418e-02,  3.4903e-03, -9.5621e-03,  ...,  2.9599e-03,
          4.3435e-04, -2.6949e-02],
        [ 2.1687e-02, -6.0216e-03,  1.4736e-02,  ..., -5.6118e-03,
 